services:
  db:
    build:
      context: ./docker/postgres
      args:
        PGVECTOR_VERSION: ${PGVECTOR_VERSION:-v0.8.3}
    container_name: postgres-postgis-pgvector
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5442:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: property_web
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_HOST: db
      HOME: /tmp
      USER: app
      LOGNAME: app
      HF_HOME: /tmp/huggingface
      TORCH_HOME: /tmp/torch
      TORCHINDUCTOR_CACHE_DIR: /tmp/torchinductor
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
