# Generated by Django 6.0.6 on 2026-06-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property_app", "0002_location_location_embedding_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="properties/%Y/%m/"),
        ),
    ]
