# Generated by Django 6.0.6 on 2026-06-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property_app", "0004_alter_propertyimage_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(max_length=100),
        ),
    ]
