# Generated by Django 6.0.6 on 2026-06-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property_app", "0006_alter_property_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
